name: cicd

on:
  push:
    branches:
      - main
    paths:
      - 'basic-infra/**'
      
defaults:
  run:
    working-directory: ./basic-infra
    
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    steps:
      - uses: actions/checkout@v3
      - name: run terraform plan
        run: terraform init && terraform plan
      - name: terraform approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GH_PAT }}
          approvers: emkej0
          issue-title: "Terraform plan and approve"
        
  terraform-apply:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    needs: terraform-plan
    steps:
      - uses: actions/checkout@v3
      - name: run terraform apply
        run: terraform init && terraform apply -auto-approve

  terraform-destroy:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    needs: terraform-apply
    if: |
      always() &&
      ( !contains(needs.*.result, 'failure') ||
      !contains(needs.*.result, 'cancelled') ||
      !contains(needs.*.result, 'skipped') )
    steps:
      - uses: actions/checkout@v3
      - name: run terraform plan
        run: terraform init && terraform plan -destroy
      - name: terraform destroy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GH_PAT }}
          approvers: emkej0
          issue-title: "Terraform plan and destroy"
      - name: run terraform destroy
        run: terraform destroy -auto-approve
