name: cicd

on:
  push:
    branches:
      - main
    paths:
      - 'basic-infra/**'
      
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    steps:
      - uses: actions/checkout@v3
      - name: run terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: terraform -chdir="./basic-infra" init && terraform -chdir="./basic-infra" plan
      - name: terraform approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: emkej0
        
  terraform-apply:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    steps:
      - uses: actions/checkout@v3
      - name: run terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: pwd && terraform -chdir="./basic-infra" apply -auto-approve
